config/routes.rb
Rubyhub2::Application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register'}
  resources :users
  resources :roles

  get "home", :controller => 'home',  :action => 'index'
  get "home/index"
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids
  # http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_and_belongs_to_many
  has_and_belongs_to_many :roles, :join_table  => 'roles_users'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #devise authentication
  #before_filter :authenticate_user!
  before_filter :get_user, :only => [:index,:new,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  # CanCan provides a convenient load_and_authorize_resource method in the controller, but what exactly is this doing? 
  	# It sets up a before filter for every action to handle the loading and authorization of the controller. 
  	# Let's say we have a typical RESTful controller with that line at the top.
  load_and_authorize_resource # :only => [:show,:new,:destroy,:edit,:update]
	#skip_authorize_resource :only => :new

  private

  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability,:read)
  end

  # Make the current user object available to views
  #----------------------------------------
  def get_user
    @current_user = current_user
  end

  public

  # GET /users
  # GET /users.xml
  # GET /users.json
  def index
    #@users = User.accessible_by(current_ability, :index).limit(20)
  	# A collection of resources is automatically loaded in the index action using accessible_by
  	 # @users automatically set to User.accessible_by(current_ability)
    # @users = @users.paginate :page => params[:page],  :per_page => 2, :order => 'updated_at DESC'
	page = params[:page] 
  	q = params[:q]
  	column = params[:column]
#  	@users = @users.paginate :per_page =>2, :page => page,
#            :conditions => ['email like ? or roles.find_by_name( ?) ', "%#{q}%", "#{q}"], :order => 'email'
  if ! column.nil? and column.downcase == 'role'
     	@users = @users.paginate  :per_page =>2, :page => page, :include => :roles,
               :conditions => ['roles.name like ? ', "%#{q}%"], :order => 'email'
  else
  	  # search email column 
     	@users = @users.paginate  :per_page =>2, :page => page, :include => :roles,
               :conditions => ['email like ? ', "%#{q}%"], :order => 'email'
   end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
      format.json { render :json => @users}
    end
  end

  # GET /users/1
  # GET /users/1.xml
  # GET /users/1.json
  def show
    #@user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
      format.json  { render :json => @user }
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # GET /users/new
  # GET /users/new.xml
  # GET /users/new.json
  def new
    #@user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
      format.json  { render :json => @user }
    end
  end

  # GET /users/1/edit
  # GET /users/1/edit.xml
  # GET /users/1/edit.json
  def edit
    #@user = User.find(params[:id])

    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # POST /users
  # POST /users.xml
  # POST /users.json
  def create
   # @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
        format.json { render :json => @user.to_json, :status => 200 }
      else
        format.html { render :action => "new", :status => :unprocessable_entity }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        format.json { render :text => "Could not create user", :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    #@user = User.find(params[:id])
    if params[:user][:password].blank?
      [:password, :password_confirmation, :current_password].collect { |p| params[:user].delete(p) }
    else
       @user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
    end
    respond_to do |format|
      if @user.errors[:base].empty?  and  @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
        format.json { render :json => @user.to_json, :status => 200 }
      else
        format.html { render :action => "edit", :status => :unprocessable_entity }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        format.json { render :text => "Could not update user", :status => :unprocessable_entity }
      end
    end
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  # DELETE /users/1.json
  def destroy
    #@user = User.find(params[:id])
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
      format.json { respond_to_destroy(:ajax)}
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
<p><%= f.label :email %><br />
<%= f.text_field :email, :disabled => true %></p>

<p><%= f.label :password %><br />
<%= f.password_field :password %></p>

<p><%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %></p>
<%
=begin %>
<% if can? :manage, @users -%>
<p><%= f.label :role %>: <%-#= f.collection_select :role, User::ROLES, :to_s, :humanize, {:include_blank => true} -%></p>
<% end -%>
<%
=end %>
<p><%= f.submit "Submit" %></p>
  </div>
<% end %>

app/views/users/_user_fields.html.erb
<p><%= f.label :email %></p>
<p><%= f.text_field :email %></p>
 
<% if can? :read, Role %>
  <p><%= f.label :role %></p>
  <ul class="no-pad no-bullets">
    <%= habtm_checkboxes(@user, :role_ids, @accessible_roles, :name, :disabled => false) -%>
  </ul>
<% end %>

app/views/users/edit.html.erb
<h3><%= @user == @current_user ? "Your Account Settings" : "Edit User" %></h3>
 
<%= form_for(@user, :html => { :method => :put }) do |f| %>
  <%= render :partial => 'user_fields', :locals => { :f => f } %>
 
  <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i></p>
  <p><%= f.password_field :password %></p>
 
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
 
  <p><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i></p>
  <p><%= f.password_field :current_password %></p>
 
  <p><%= f.submit "Update" %></p>
<% end %>


<%= link_to "Back", :back %> | 
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<div style="float:left;  padding:5px; background-color:#DEDFFE;border: 1px solid #DEDFDE;"> 
	<%= page_entries_info @roles -%></div>
<div style="float:right;">	
	<%= form_tag request.path, :method => 'get' do %>
	  <%= content_tag :label do %>
	  	<%-#= select_tag :column, raw("<option value='email'>Email</option><option value='role'>Role</option>")-%>
		<%= select_tag :column, options_for_select(["email", "role"], params[:column]) %>

	    Search term:
	    <%= text_field_tag :q, params[:q] %>
	  <% end %>
	<% end %>
</div>

<br clear="left"/>
<table>
	<thead>
		<tr><td>Email</td><td>Roles</td><td>updated_at</td><td>created_at</td>
			<td colspan=6></td></tr>
	</thead>
<% @users.each do |u| %>
  <tr>
    <td><%= link_to( "#{u.email}", user_path(u.id))  -%></td>
  
    <td><%= "#{u.roles.collect{|r| r.name}}" %></td>
    <td><%= "#{u.updated_at}"%></td>
    <td><%= "#{u.created_at}" %> </td>
    <td><%= link_to_if(can?(:edit, User), image_tag("/images/edit_icon.gif"), edit_user_path(u.id)) {} %></td>
    <td><%= link_to_if(can?(:delete, u), image_tag("/images/delete_icon.gif"), u, :confirm => "Are you sure?", :method => :delete) {} %></td>
  	<td></td>
    <td><%= link_to 'Show', u %></td>
    <td><%= link_to 'Edit', edit_user_path(u) %></td>
    <td><%= link_to 'Destroy', u, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
  <div class='flickr_pagination'><%= will_paginate @users %> </div>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2>Register User</h2>
 
<%= form_for(@user) do |f| %>
 
  <%= render :partial => 'user_fields', :locals => { :f => f } %>
 
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
 
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
 
  <p><%= f.submit "Register" %></p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h3><%= @user.email %></h3>
 
<%= link_to_if(can?(:update,@user), "Edit", edit_user_path(@user)) %> |
<%= link_to_if(can?(:delete, @user), "Delete", user_path(@user), :confirm => "Are you sure?", :method => :delete) {} %>
 
<table class="one-column-emphasis">
  <tbody>
    <tr>
      <td class="oce-first">Email:</td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td class="oce-first">Role:</td>
      <td><%=  "#{@user.roles.collect{|r| r.name}}"  %>
      </td>
    </tr>
  <% if can?(:see_timestamps,User) %>
    <tr>
      <td class="oce-first">Created at:</td>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <td class="oce-first">Last Sign In:</td>
      <td><%= @user.last_sign_in_at %></td>
    </tr>
    <tr>
      <td class="oce-first">Sign In Count:</td>
      <td><%= @user.sign_in_count %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>