config/routes.rb
Rubyhub2::Application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register'}
  resources :users
  resources :roles

  get "home", :controller => 'home',  :action => 'index'
  get "home/index"
  root :to => "home#index"

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table  => 'roles_users'
  
  def self.search( q, page)
    paginate :per_page =>2, :page => page,
                    :conditions => ['name like ?', "%#{q}%"], :order => 'name'
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  load_and_authorize_resource # :only => [:show,:new,:destroy,:edit,:update]

  # GET /roles
  # GET /roles.xml
  def index
    #will_paginate simple search
    @roles = Role.search(params[:q], params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>
<div style="float:left;  padding:5px; background-color:#DEDFFE;border: 1px solid #DEDFDE;"> <%= page_entries_info @roles -%></div>
<div style="float:right;">	
	<%= form_tag request.path, :method => 'get' do %>
	  <%= content_tag :label do %>
	    Search term:
	    <%= text_field_tag :q, params[:q] %>
	  <% end %>
	<% end %>
</div>

<br clear=left/>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
  <div class='flickr_pagination'><%= will_paginate @roles %> </div>
<br/>
<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>